--- #YAML:1.0
name:               Games-Tetris-Complete
version:            0.02
abstract:           Play Tetris from the console
author:
    - Blake Willmarth <bwillmarth@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:              1.18
    Term::ReadKey:      0
    Term::Screen::Uni:  0
    Test::More:         0
    Thread::Semaphore:  0
    Time::HiRes:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
